"""empty message

Revision ID: aaebb237553c
Revises: a2c4d6e289f5
Create Date: 2024-01-31 23:08:30.898300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaebb237553c'
down_revision = 'a2c4d6e289f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_list', schema=None) as batch_op:
        batch_op.drop_constraint('personal_list_view_state_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_list', schema=None) as batch_op:
        batch_op.create_unique_constraint('personal_list_view_state_key', ['view_state'])

    # ### end Alembic commands ###
